#!/bin/bash

# for running locally
if [ "$1" != "" ]; then
	export BUILD="$1"
fi

if [ -z "$BUILD" ]; then
  export BUILD=$(date +%Y%m%d.%H%M%S)
fi

cmd() {
	echo ">>>"
  echo ">>> $@"
	echo ">>>"
  "$@"
}

cmd ./docker/base/build

echo "--- docker/release/build-local"
cmd docker build --build-arg BUILD_VERSION=$BUILD \
	-f docker/release/Dockerfile -t saasy-backend:$BUILD . &&
  cmd docker tag saasy-backend:$BUILD saasy-backend:latest
